eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order #\u670D\u52A1\u540D\u79F0
  datasource:
    username: root
    password: accp
    url: jdbc:mysql://localhost:3306/pm208?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090

  #\u4FEE\u6539\u6211\u4EEC\u81EA\u5DF1\u7684\u4EA7\u54C1\u670D\u52A1\u4E3A\u968F\u673A\u7B56\u7565
product:
  ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
