env: product-dev
spring:
  datasource:
    username: root
    password: accp
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pm208?serverTimezone=GMT

  application:
    name: product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
